#!/usr/bin/env bash
# This Script connects to the server 34.204.91.91 using the users private key
# stored in a file school Found in the users home directory

ssh -i ~/.ssh/school ubuntu@54.236.25.112
